import React, { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

const translations = {
  en: {
    nav_home: 'Home',
    nav_services: 'Services',
    nav_concierge: 'Concierge',
    nav_contact: 'Contact',
    nav_luxury_cars: 'Luxury Cars',
    nav_luxury_properties: 'Luxury Properties',
    hero_title: 'Exceptional Luxury',
    hero_subtitle: 'Discover the finest properties and vehicles in Dubai',
    btn_explore: 'Explore Properties',
    btn_concierge: 'Concierge Services',
    services_title: 'Our Premium Services',
    properties_title: 'Luxury Properties',
    properties_desc: 'Exclusive villas and penthouses in Dubai\'s most prestigious locations.',
    vehicles_title: 'Exotic Vehicles',
    vehicles_desc: 'From limited edition supercars to custom luxury vehicles.',
    concierge_title: 'Concierge Services',
    concierge_desc: 'Personalized assistance for our distinguished clientele.',
    stat_experience: 'Years Experience',
    stat_clients: 'Happy Clients',
    stat_satisfaction: 'Satisfaction',
    btn_view_more: 'View More',
    btn_view_details: 'View Details',
    contact_whatsapp: 'Contact via WhatsApp',
    contact_email: 'Contact via Email',
    whatsapp: 'WhatsApp',
    email: 'Email',
    phone: 'Phone',
    contact_banner_subtitle: 'Get in touch with our luxury specialists',
    for_immediate_assistance_quick: 'For immediate assistance and quick inquiries',
    for_detailed_inquiries_info: 'For detailed inquiries and information',
    speak_directly: 'Speak directly with our team',
    send_message: 'Send Us a Message',
    full_name: 'Full Name',
    email_address: 'Email Address',
    phone_number: 'Phone Number',
    subject: 'Subject',
    your_message: 'Your Message',
    btn_send_message: 'Send Message',
    our_offices: 'Our Offices',
    offices_subtitle: 'Visit us at our prestigious locations worldwide',
    discover_collection: 'Discover our exclusive collection of luxury properties and vehicles',
    exclusive_villas: 'Exclusive villas and penthouses in Dubai\'s most prestigious locations',
    luxury_concierge: 'Luxury Concierge',
    concierge_service_desc: 'Our exclusive concierge service is designed to cater to your every need, providing personalized assistance and access to the most exclusive experiences in Dubai and beyond.',
    personalized_experiences: 'Personalized luxury experiences tailored to your desires',
    travel_arrangements: 'Travel Arrangements',
    travel_desc: 'Private jet charters, luxury yacht rentals, VIP airport transfers, and bespoke travel itineraries tailored to your preferences.',
    dining_experiences: 'Dining Experiences',
    dining_desc: 'Reservations at exclusive restaurants, private chef services, culinary tours, and access to Michelin-starred dining establishments.',
    event_access: 'Event Access',
    event_desc: 'VIP tickets to sold-out events, exclusive private parties, cultural experiences, and access to the most prestigious gatherings.',
    personal_shopping: 'Personal Shopping',
    shopping_desc: 'Exclusive shopping experiences, access to limited collections, personal styling services, and private shopping appointments.',
    wellness_services: 'Wellness Services',
    wellness_desc: 'Private spa treatments, personal wellness consultations, fitness trainers, and holistic health experiences.',
    special_occasions: 'Special Occasions',
    occasions_desc: 'Bespoke event planning for celebrations, weddings, anniversaries, and special moments with meticulous attention to detail.',
    book_service: 'Book Service',
    get_in_touch: 'Get In Touch',
    contact_form_desc: 'Fill out the form below or contact us directly via WhatsApp or Email',
    chat_with_us: 'Chat with Us',
    send_email: 'Send Email',
    call_us: 'Call Us',
    quick_links: 'Quick Links',
    contact_us: 'Contact Us',
    for_immediate_assistance: 'For immediate assistance',
    for_detailed_inquiries: 'For detailed inquiries',
    // Admin translations
    admin_dashboard: 'Dashboard',
    admin_cars: 'Cars',
    admin_properties: 'Properties',
    admin_concierge: 'Concierge',
    admin_messages: 'Messages',
    admin_users: 'Users',
    admin_settings: 'Settings',
    admin_logout: 'Logout',
    admin_view_website: 'View Website',
    admin_welcome_back: 'Welcome back',
    admin_add_car: 'Add Car',
    admin_add_property: 'Add Property',
    admin_add_service: 'Add Service',
    admin_add_admin: 'Add Admin',
    admin_edit: 'Edit',
    admin_delete: 'Delete',
    admin_save: 'Save',
    admin_cancel: 'Cancel',
    admin_update: 'Update',
    admin_total_cars: 'Total Cars',
    admin_total_properties: 'Total Properties',
    admin_concierge_services: 'Concierge Services',
    admin_active_users: 'Active Users',
    admin_quick_actions: 'Quick Actions',
    admin_recent_messages: 'Recent Messages',
    admin_system_status: 'System Status',
    admin_all_systems_operational: 'All Systems Operational',
    admin_online: 'Online',
    admin_storage_usage: 'Storage Usage',
    admin_manage_inventory: 'Manage your vehicle inventory',
    admin_manage_listings: 'Manage your property listings',
    admin_manage_offerings: 'Manage concierge offerings',
    admin_manage_inquiries: 'Manage customer inquiries',
    admin_manage_accounts: 'Manage admin accounts',
    admin_global_settings: 'Manage global site configuration',
    admin_car_name: 'Car Name',
    admin_folder_name: 'Folder Name',
    admin_year: 'Year',
    admin_transmission: 'Transmission',
    admin_color: 'Color',
    admin_images_upload: 'Images Upload (4-6 images)',
    admin_images_count: 'images',
    admin_reply_via_email: 'Reply via Email',
    admin_reply_via_whatsapp: 'Reply via WhatsApp',
    admin_new_car: 'Add New Car',
    admin_edit_car: 'Edit Car',
    admin_new_property: 'Add New Property',
    admin_edit_property: 'Edit Property',
    admin_new_service: 'Add New Service',
    admin_edit_service: 'Edit Service',
    admin_no_messages: 'No messages yet',
    admin_no_listings: 'No listings yet',
    admin_name: 'Name',
    admin_role: 'Role',
    admin_status: 'Status',
    admin_created: 'Created',
    admin_actions: 'Actions',
    admin_active: 'active',
    admin_inactive: 'inactive',
    admin_site_name: 'Site Name',
    admin_default_language: 'Default Language',
    admin_logo_upload: 'Logo Upload',
    admin_current_theme: 'Current Theme',
    admin_dark_mode: 'Dark Mode',
    admin_light_mode: 'Light Mode',
    admin_primary_color: 'Primary Color (Gold)',
    admin_secondary_color: 'Secondary Color (Purple)',
    admin_contact_info: 'Contact Information',
    admin_whatsapp: 'WhatsApp',
    admin_address: 'Address',
    admin_save_settings: 'Save Settings',
    admin_settings_saved: 'Settings saved successfully',
    admin_manage_inventory_desc: 'Manage your vehicle inventory',
    admin_manage_listings_desc: 'Manage your property listings',
    admin_manage_offerings_desc: 'Manage concierge offerings',
    admin_manage_inquiries_desc: 'Manage customer inquiries',
    admin_manage_accounts_desc: 'Manage admin accounts',
    admin_manage_config: 'Manage global site configuration',
    admin_client_messages: 'Client Messages',
    admin_user_management: 'User Management',
    admin_ready_to_experience: 'Ready to Experience Luxury?',
    admin_contact_team: 'Contact our team today to discover how we can help you find your perfect luxury property or vehicle',
  },
  fr: {
    nav_home: 'Accueil',
    nav_services: 'Services',
    nav_concierge: 'Conciergerie',
    nav_contact: 'Contact',
    nav_luxury_cars: 'Voitures de Luxe',
    nav_luxury_properties: 'Propriétés de Luxe',
    hero_title: 'Luxe Exceptionnel',
    hero_subtitle: 'Découvrez les propriétés et véhicules les plus raffinés de Dubaï',
    btn_explore: 'Explorer les Propriétés',
    btn_concierge: 'Services de Conciergerie',
    services_title: 'Nos Services Premium',
    properties_title: 'Propriétés de Luxe',
    properties_desc: 'Villas et penthouse exclusifs dans les emplacements les plus prestigieux de Dubaï.',
    vehicles_title: 'Véhicules Exotiques',
    vehicles_desc: 'Des supercars en édition limitée aux véhicules de luxe sur mesure.',
    concierge_title: 'Services de Conciergerie',
    concierge_desc: 'Assistance personnalisée pour notre clientèle distinguée.',
    stat_experience: 'Années d\'Expérience',
    stat_clients: 'Clients Heureux',
    stat_satisfaction: 'Satisfaction',
    btn_view_more: 'Voir Plus',
    btn_view_details: 'Voir les Détails',
    contact_whatsapp: 'Contacter via WhatsApp',
    contact_email: 'Contacter par E-mail',
    whatsapp: 'WhatsApp',
    email: 'E-mail',
    phone: 'Téléphone',
    contact_banner_subtitle: 'Contactez nos spécialistes du luxe',
    for_immediate_assistance_quick: 'Pour une assistance immédiate et des demandes rapides',
    for_detailed_inquiries_info: 'Pour des demandes détaillées et des informations',
    speak_directly: 'Parlez directement avec notre équipe',
    send_message: 'Envoyez-nous un Message',
    full_name: 'Nom Complet',
    email_address: 'Adresse E-mail',
    phone_number: 'Numéro de Téléphone',
    subject: 'Sujet',
    your_message: 'Votre Message',
    btn_send_message: 'Envoyer le Message',
    our_offices: 'Nos Bureaux',
    offices_subtitle: 'Visitez-nous dans nos emplacements prestigieux à travers le monde',
    discover_collection: 'Découvrez notre collection exclusive de propriétés et véhicules de luxe',
    exclusive_villas: 'Villas et penthouse exclusifs dans les emplacements les plus prestigieux de Dubaï',
    luxury_concierge: 'Conciergerie de Luxe',
    concierge_service_desc: 'Notre service de conciergerie exclusif est conçu pour répondre à tous vos besoins, offrant une assistance personnalisée et un accès aux expériences les plus exclusives de Dubaï et au-delà.',
    personalized_experiences: 'Expériences de luxe personnalisées adaptées à vos désirs',
    travel_arrangements: 'Arrangements de Voyage',
    travel_desc: 'Charters d\'avions privés, location de yachts de luxe, transferts aéroport VIP et itinéraires de voyage sur mesure adaptés à vos préférences.',
    dining_experiences: 'Expériences Culinaires',
    dining_desc: 'Réservations dans des restaurants exclusifs, services de chef privé, visites culinaires et accès aux établissements gastronomiques étoilés Michelin.',
    event_access: 'Accès aux Événements',
    event_desc: 'Billets VIP pour des événements complets, fêtes privées exclusives, expériences culturelles et accès aux rassemblements les plus prestigieux.',
    personal_shopping: 'Shopping Personnel',
    shopping_desc: 'Expériences de shopping exclusives, accès aux collections limitées, services de stylisme personnel et rendez-vous de shopping privés.',
    wellness_services: 'Services de Bien-être',
    wellness_desc: 'Traitements spa privés, consultations de bien-être personnelles, entraîneurs de fitness et expériences de santé holistiques.',
    special_occasions: 'Occasions Spéciales',
    occasions_desc: 'Planification d\'événements sur mesure pour les célébrations, mariages, anniversaires et moments spéciaux avec une attention méticuleuse aux détails.',
    book_service: 'Réserver un Service',
    get_in_touch: 'Contactez-nous',
    contact_form_desc: 'Remplissez le formulaire ci-dessous ou contactez-nous directement via WhatsApp ou E-mail',
    chat_with_us: 'Discutez avec Nous',
    send_email: 'Envoyer un E-mail',
    call_us: 'Appelez-nous',
    quick_links: 'Liens Rapides',
    contact_us: 'Contactez-nous',
    for_immediate_assistance: 'Pour une assistance immédiate',
    for_detailed_inquiries: 'Pour des demandes détaillées',
    // Admin translations (French)
    admin_dashboard: 'Tableau de Bord',
    admin_cars: 'Voitures',
    admin_properties: 'Propriétés',
    admin_concierge: 'Conciergerie',
    admin_messages: 'Messages',
    admin_users: 'Utilisateurs',
    admin_settings: 'Paramètres',
    admin_logout: 'Déconnexion',
    admin_view_website: 'Voir le Site',
    admin_welcome_back: 'Bon retour',
    admin_add_car: 'Ajouter une Voiture',
    admin_add_property: 'Ajouter une Propriété',
    admin_add_service: 'Ajouter un Service',
    admin_add_admin: 'Ajouter un Admin',
    admin_edit: 'Modifier',
    admin_delete: 'Supprimer',
    admin_save: 'Enregistrer',
    admin_cancel: 'Annuler',
    admin_update: 'Mettre à Jour',
    admin_total_cars: 'Total Voitures',
    admin_total_properties: 'Total Propriétés',
    admin_concierge_services: 'Services de Conciergerie',
    admin_active_users: 'Utilisateurs Actifs',
    admin_quick_actions: 'Actions Rapides',
    admin_recent_messages: 'Messages Récents',
    admin_system_status: 'Statut du Système',
    admin_all_systems_operational: 'Tous les Systèmes Opérationnels',
    admin_online: 'En Ligne',
    admin_storage_usage: 'Utilisation du Stockage',
    admin_manage_inventory: 'Gérez votre inventaire de véhicules',
    admin_manage_listings: 'Gérez vos annonces de propriétés',
    admin_manage_offerings: 'Gérez les offres de conciergerie',
    admin_manage_inquiries: 'Gérez les demandes des clients',
    admin_manage_accounts: 'Gérez les comptes administrateur',
    admin_global_settings: 'Gérer la configuration globale du site',
    admin_car_name: 'Nom de la Voiture',
    admin_folder_name: 'Nom du Dossier',
    admin_year: 'Année',
    admin_transmission: 'Transmission',
    admin_color: 'Couleur',
    admin_images_upload: 'Téléchargement d\'Images (4-6 images)',
    admin_images_count: 'images',
    admin_reply_via_email: 'Répondre par E-mail',
    admin_reply_via_whatsapp: 'Répondre par WhatsApp',
    admin_new_car: 'Ajouter une Nouvelle Voiture',
    admin_edit_car: 'Modifier la Voiture',
    admin_new_property: 'Ajouter une Nouvelle Propriété',
    admin_edit_property: 'Modifier la Propriété',
    admin_new_service: 'Ajouter un Nouveau Service',
    admin_edit_service: 'Modifier le Service',
    admin_no_messages: 'Aucun message pour le moment',
    admin_no_listings: 'Aucune annonce pour le moment',
    admin_name: 'Nom',
    admin_role: 'Rôle',
    admin_status: 'Statut',
    admin_created: 'Créé',
    admin_actions: 'Actions',
    admin_active: 'actif',
    admin_inactive: 'inactif',
    admin_site_name: 'Nom du Site',
    admin_default_language: 'Langue par Défaut',
    admin_logo_upload: 'Téléchargement du Logo',
    admin_current_theme: 'Thème Actuel',
    admin_dark_mode: 'Mode Sombre',
    admin_light_mode: 'Mode Clair',
    admin_primary_color: 'Couleur Principale (Or)',
    admin_secondary_color: 'Couleur Secondaire (Violet)',
    admin_contact_info: 'Informations de Contact',
    admin_whatsapp: 'WhatsApp',
    admin_address: 'Adresse',
    admin_save_settings: 'Enregistrer les Paramètres',
    admin_settings_saved: 'Paramètres enregistrés avec succès',
    admin_manage_inventory_desc: 'Gérez votre inventaire de véhicules',
    admin_manage_listings_desc: 'Gérez vos annonces de propriétés',
    admin_manage_offerings_desc: 'Gérez les offres de conciergerie',
    admin_manage_inquiries_desc: 'Gérez les demandes des clients',
    admin_manage_accounts_desc: 'Gérez les comptes administrateur',
    admin_manage_config: 'Gérer la configuration globale du site',
    admin_client_messages: 'Messages Clients',
    admin_user_management: 'Gestion des Utilisateurs',
    admin_ready_to_experience: 'Prêt à Vivre le Luxe ?',
    admin_contact_team: 'Contactez notre équipe dès aujourd\'hui pour découvrir comment nous pouvons vous aider à trouver votre propriété ou véhicule de luxe idéal',
  }
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en'
  })

  useEffect(() => {
    localStorage.setItem('language', language)
    document.documentElement.lang = language
  }, [language])

  const t = (key) => {
    return translations[language]?.[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}

