import React, { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

const translations = {
  en: {
    site_name: 'Don Pépé Services',
    site_tagline: 'Luxury Beyond Limits',
    meta_description: "Don Pépé Services - Luxury Beyond Limits. Discover exclusive properties, premium vehicles, and concierge services in Dubai.",
    email_subject_contact: 'Inquiry from Don Pépé Services Website',
    nav_home: 'Home',
    nav_services: 'Services',
    nav_concierge: 'Concierge',
    nav_contact: 'Contact',
    nav_luxury_cars: 'Luxury Cars',
    nav_luxury_properties: 'Luxury Properties',
    hero_title: 'Exceptional Luxury',
    hero_subtitle: 'Discover the finest properties and vehicles in Dubai',
    btn_explore: 'Explore Properties',
    btn_concierge: 'Concierge Services',
    services_title: 'Our Premium Services',
    properties_title: 'Luxury Properties',
    properties_desc: 'Exclusive villas and penthouses in Dubai\'s most prestigious locations.',
    vehicles_title: 'Exotic Vehicles',
    vehicles_desc: 'From limited edition supercars to custom luxury vehicles.',
    concierge_title: 'Concierge Services',
    concierge_desc: 'Personalized assistance for our distinguished clientele.',
    stat_experience: 'Years Experience',
    stat_clients: 'Happy Clients',
    stat_satisfaction: 'Satisfaction',
    btn_view_more: 'View More',
    btn_view_details: 'View Details',
    contact_whatsapp: 'Contact via WhatsApp',
    contact_email: 'Contact via Email',
    whatsapp: 'WhatsApp',
    email: 'Email',
    phone: 'Phone',
    contact_banner_subtitle: 'Get in touch with our luxury specialists',
    for_immediate_assistance_quick: 'For immediate assistance and quick inquiries',
    for_detailed_inquiries_info: 'For detailed inquiries and information',
    speak_directly: 'Speak directly with our team',
    send_message: 'Send Us a Message',
    full_name: 'Full Name',
    email_address: 'Email Address',
    phone_number: 'Phone Number',
    subject: 'Subject',
    your_message: 'Your Message',
    btn_send_message: 'Send Message',
    our_offices: 'Our Offices',
    offices_subtitle: 'Visit us at our prestigious locations worldwide',
    discover_collection: 'Discover our exclusive collection of luxury properties and vehicles',
    exclusive_villas: 'Exclusive villas and penthouses in Dubai\'s most prestigious locations',
    luxury_concierge: 'Luxury Concierge',
    concierge_service_desc: 'Our exclusive concierge service is designed to cater to your every need, providing personalized assistance and access to the most exclusive experiences in Dubai and beyond.',
    personalized_experiences: 'Personalized luxury experiences tailored to your desires',
    travel_arrangements: 'Travel Arrangements',
    travel_desc: 'Private jet charters, luxury yacht rentals, VIP airport transfers, and bespoke travel itineraries tailored to your preferences.',
    dining_experiences: 'Dining Experiences',
    dining_desc: 'Reservations at exclusive restaurants, private chef services, culinary tours, and access to Michelin-starred dining establishments.',
    event_access: 'Event Access',
    event_desc: 'VIP tickets to sold-out events, exclusive private parties, cultural experiences, and access to the most prestigious gatherings.',
    personal_shopping: 'Personal Shopping',
    shopping_desc: 'Exclusive shopping experiences, access to limited collections, personal styling services, and private shopping appointments.',
    wellness_services: 'Wellness Services',
    wellness_desc: 'Private spa treatments, personal wellness consultations, fitness trainers, and holistic health experiences.',
    special_occasions: 'Special Occasions',
    occasions_desc: 'Bespoke event planning for celebrations, weddings, anniversaries, and special moments with meticulous attention to detail.',
    book_service: 'Book Service',
    get_in_touch: 'Get In Touch',
    contact_form_desc: 'Fill out the form below or contact us directly via WhatsApp or Email',
    chat_with_us: 'Chat with Us',
    send_email: 'Send Email',
    call_us: 'Call Us',
    quick_links: 'Quick Links',
    contact_us: 'Contact Us',
    for_immediate_assistance: 'For immediate assistance',
    for_detailed_inquiries: 'For detailed inquiries',
    // Admin translations
    admin_dashboard: 'Dashboard',
    admin_cars: 'Cars',
    admin_properties: 'Properties',
    admin_concierge: 'Concierge',
    admin_messages: 'Messages',
    admin_users: 'Users',
    admin_settings: 'Settings',
    admin_logout: 'Logout',
    admin_view_website: 'View Website',
    admin_welcome_back: 'Welcome back',
    admin_add_car: 'Add Car',
    admin_add_property: 'Add Property',
    admin_add_service: 'Add Service',
    admin_add_admin: 'Add Admin',
    admin_edit: 'Edit',
    admin_delete: 'Delete',
    admin_save: 'Save',
    admin_cancel: 'Cancel',
    admin_update: 'Update',
    admin_total_cars: 'Total Cars',
    admin_total_properties: 'Total Properties',
    admin_concierge_services: 'Concierge Services',
    admin_active_users: 'Active Users',
    admin_quick_actions: 'Quick Actions',
    admin_recent_messages: 'Recent Messages',
    admin_system_status: 'System Status',
    admin_all_systems_operational: 'All Systems Operational',
    admin_online: 'Online',
    admin_storage_usage: 'Storage Usage',
    admin_manage_inventory: 'Manage your vehicle inventory',
    admin_manage_listings: 'Manage your property listings',
    admin_manage_offerings: 'Manage concierge offerings',
    admin_manage_inquiries: 'Manage customer inquiries',
    admin_manage_accounts: 'Manage admin accounts',
    admin_global_settings: 'Manage global site configuration',
    admin_car_name: 'Car Name',
    admin_folder_name: 'Folder Name',
    admin_year: 'Year',
    admin_transmission: 'Transmission',
    admin_color: 'Color',
    admin_images_upload: 'Images Upload (4-6 images)',
    admin_images_count: 'images',
    admin_reply_via_email: 'Reply via Email',
    admin_reply_via_whatsapp: 'Reply via WhatsApp',
    admin_new_car: 'Add New Car',
    admin_edit_car: 'Edit Car',
    admin_new_property: 'Add New Property',
    admin_edit_property: 'Edit Property',
    admin_new_service: 'Add New Service',
    admin_edit_service: 'Edit Service',
    admin_no_messages: 'No messages yet',
    admin_no_listings: 'No listings yet',
    admin_name: 'Name',
    admin_role: 'Role',
    admin_status: 'Status',
    admin_created: 'Created',
    admin_actions: 'Actions',
    admin_active: 'active',
    admin_inactive: 'inactive',
    admin_site_name: 'Site Name',
    admin_default_language: 'Default Language',
    admin_logo_upload: 'Logo Upload',
    admin_current_theme: 'Current Theme',
    admin_dark_mode: 'Dark Mode',
    admin_light_mode: 'Light Mode',
    admin_primary_color: 'Primary Color (Gold)',
    admin_secondary_color: 'Secondary Color (Purple)',
    admin_contact_info: 'Contact Information',
    admin_whatsapp: 'WhatsApp',
    admin_address: 'Address',
    admin_save_settings: 'Save Settings',
    admin_settings_saved: 'Settings saved successfully',
    admin_manage_inventory_desc: 'Manage your vehicle inventory',
    admin_manage_listings_desc: 'Manage your property listings',
    admin_manage_offerings_desc: 'Manage concierge offerings',
    admin_manage_inquiries_desc: 'Manage customer inquiries',
    admin_manage_accounts_desc: 'Manage admin accounts',
    admin_manage_config: 'Manage global site configuration',
    admin_client_messages: 'Client Messages',
    admin_user_management: 'User Management',
    admin_ready_to_experience: 'Ready to Experience Luxury?',
    admin_contact_team: 'Contact our team today to discover how we can help you find your perfect luxury property or vehicle',
    // Home page translations
    home_about_title: 'About Don Pépé Services',
    home_about_p1: 'Don Pépé Services is Dubai\'s premier luxury marketplace, specializing in exclusive real estate, premium vehicles, and bespoke concierge services. With over 15 years of experience serving distinguished clientele worldwide, we curate only the finest properties and vehicles.',
    home_about_p2: 'Our portfolio includes stunning beachfront villas on Palm Jumeirah, luxurious penthouses in Downtown Dubai with Burj Khalifa views, and elegant mansions in Emirates Hills. Each property is carefully selected to meet the highest standards of luxury and sophistication.',
    home_about_p3: 'Our vehicle collection features the world\'s most exclusive automobiles, from limited edition supercars to custom luxury vehicles. We work directly with manufacturers and collectors to bring you access to vehicles that are rarely available on the open market.',
    home_services_subtitle: 'Experience unparalleled luxury with our exclusive collection of properties, vehicles, and services',
    home_why_choose_title: 'Why Choose Don Pépé',
    home_why_choose_subtitle: 'What sets us apart in the luxury market',
    home_why_excellence: 'Excellence',
    home_why_excellence_desc: 'Award-winning service recognized by luxury industry leaders',
    home_why_trusted_network: 'Trusted Network',
    home_why_trusted_desc: 'Access to exclusive listings and private collections worldwide',
    home_why_security: 'Security',
    home_why_security_desc: 'Complete confidentiality and secure transactions for all clients',
    home_why_support: '24/7 Support',
    home_why_support_desc: 'Dedicated concierge team available around the clock for your needs',
    home_cta_ready: 'Ready to Experience Luxury?',
    home_cta_contact: 'Contact our team today to discover how we can help you find your perfect luxury property or vehicle',
    home_cta_get_started: 'Get Started',
    // Services page translations
    services_search_placeholder: 'Search cars by name, brand, or model...',
    services_search_no_results: 'No cars match your search.',
    services_search_found: 'Found {count} {plural}',
    services_search_found_car: 'car',
    services_search_found_cars: 'cars',
    services_no_results_title: 'No cars match your search',
    services_no_results_desc: 'Try adjusting your search terms or browse all our luxury vehicles',
    services_clear_search: 'Clear Search',
    services_vehicles_desc: 'From limited edition supercars to custom luxury vehicles',
    services_beds: 'Beds',
    services_baths: 'Baths',
    services_sqft: 'sqft',
    // Contact page
    concierge_service_inquiry: 'Concierge Service Inquiry',
    // Common UI elements
    logo_alt: 'Don Pépé Logo',
    admin_login_portal: 'Don Pépé Admin',
    admin_login_access: 'Secure Access Portal',
    admin_login_error: 'Login failed. Please check your credentials.',
    admin_login_submit: 'Sign In',
  },
  fr: {
    site_name: 'Don Pépé Services',
    site_tagline: 'Luxe Exceptionnel',
    meta_description: "Don Pépé Services - Luxe Exceptionnel. Découvrez des propriétés et véhicules de luxe à Dubaï.",
    email_subject_contact: 'Demande depuis le site Don Pépé Services',
    nav_home: 'Accueil',
    nav_services: 'Services',
    nav_concierge: 'Conciergerie',
    nav_contact: 'Contact',
    nav_luxury_cars: 'Voitures de Luxe',
    nav_luxury_properties: 'Propriétés de Luxe',
    hero_title: 'Luxe Exceptionnel',
    hero_subtitle: 'Découvrez les propriétés et véhicules les plus raffinés de Dubaï',
    btn_explore: 'Explorer les Propriétés',
    btn_concierge: 'Services de Conciergerie',
    services_title: 'Nos Services Premium',
    properties_title: 'Propriétés de Luxe',
    properties_desc: 'Villas et penthouse exclusifs dans les emplacements les plus prestigieux de Dubaï.',
    vehicles_title: 'Véhicules Exotiques',
    vehicles_desc: 'Des supercars en édition limitée aux véhicules de luxe sur mesure.',
    concierge_title: 'Services de Conciergerie',
    concierge_desc: 'Assistance personnalisée pour notre clientèle distinguée.',
    stat_experience: 'Années d\'Expérience',
    stat_clients: 'Clients Heureux',
    stat_satisfaction: 'Satisfaction',
    btn_view_more: 'Voir Plus',
    btn_view_details: 'Voir les Détails',
    contact_whatsapp: 'Contacter via WhatsApp',
    contact_email: 'Contacter par E-mail',
    whatsapp: 'WhatsApp',
    email: 'E-mail',
    phone: 'Téléphone',
    contact_banner_subtitle: 'Contactez nos spécialistes du luxe',
    for_immediate_assistance_quick: 'Pour une assistance immédiate et des demandes rapides',
    for_detailed_inquiries_info: 'Pour des demandes détaillées et des informations',
    speak_directly: 'Parlez directement avec notre équipe',
    send_message: 'Envoyez-nous un Message',
    full_name: 'Nom Complet',
    email_address: 'Adresse E-mail',
    phone_number: 'Numéro de Téléphone',
    subject: 'Sujet',
    your_message: 'Votre Message',
    btn_send_message: 'Envoyer le Message',
    our_offices: 'Nos Bureaux',
    offices_subtitle: 'Visitez-nous dans nos emplacements prestigieux à travers le monde',
    discover_collection: 'Découvrez notre collection exclusive de propriétés et véhicules de luxe',
    exclusive_villas: 'Villas et penthouse exclusifs dans les emplacements les plus prestigieux de Dubaï',
    luxury_concierge: 'Conciergerie de Luxe',
    concierge_service_desc: 'Notre service de conciergerie exclusif est conçu pour répondre à tous vos besoins, offrant une assistance personnalisée et un accès aux expériences les plus exclusives de Dubaï et au-delà.',
    personalized_experiences: 'Expériences de luxe personnalisées adaptées à vos désirs',
    travel_arrangements: 'Arrangements de Voyage',
    travel_desc: 'Charters d\'avions privés, location de yachts de luxe, transferts aéroport VIP et itinéraires de voyage sur mesure adaptés à vos préférences.',
    dining_experiences: 'Expériences Culinaires',
    dining_desc: 'Réservations dans des restaurants exclusifs, services de chef privé, visites culinaires et accès aux établissements gastronomiques étoilés Michelin.',
    event_access: 'Accès aux Événements',
    event_desc: 'Billets VIP pour des événements complets, fêtes privées exclusives, expériences culturelles et accès aux rassemblements les plus prestigieux.',
    personal_shopping: 'Shopping Personnel',
    shopping_desc: 'Expériences de shopping exclusives, accès aux collections limitées, services de stylisme personnel et rendez-vous de shopping privés.',
    wellness_services: 'Services de Bien-être',
    wellness_desc: 'Traitements spa privés, consultations de bien-être personnelles, entraîneurs de fitness et expériences de santé holistiques.',
    special_occasions: 'Occasions Spéciales',
    occasions_desc: 'Planification d\'événements sur mesure pour les célébrations, mariages, anniversaires et moments spéciaux avec une attention méticuleuse aux détails.',
    book_service: 'Réserver un Service',
    get_in_touch: 'Contactez-nous',
    contact_form_desc: 'Remplissez le formulaire ci-dessous ou contactez-nous directement via WhatsApp ou E-mail',
    chat_with_us: 'Discutez avec Nous',
    send_email: 'Envoyer un E-mail',
    call_us: 'Appelez-nous',
    quick_links: 'Liens Rapides',
    contact_us: 'Contactez-nous',
    for_immediate_assistance: 'Pour une assistance immédiate',
    for_detailed_inquiries: 'Pour des demandes détaillées',
    // Admin translations (French)
    admin_dashboard: 'Tableau de Bord',
    admin_cars: 'Voitures',
    admin_properties: 'Propriétés',
    admin_concierge: 'Conciergerie',
    admin_messages: 'Messages',
    admin_users: 'Utilisateurs',
    admin_settings: 'Paramètres',
    admin_logout: 'Déconnexion',
    admin_view_website: 'Voir le Site',
    admin_welcome_back: 'Bon retour',
    admin_add_car: 'Ajouter une Voiture',
    admin_add_property: 'Ajouter une Propriété',
    admin_add_service: 'Ajouter un Service',
    admin_add_admin: 'Ajouter un Admin',
    admin_edit: 'Modifier',
    admin_delete: 'Supprimer',
    admin_save: 'Enregistrer',
    admin_cancel: 'Annuler',
    admin_update: 'Mettre à Jour',
    admin_total_cars: 'Total Voitures',
    admin_total_properties: 'Total Propriétés',
    admin_concierge_services: 'Services de Conciergerie',
    admin_active_users: 'Utilisateurs Actifs',
    admin_quick_actions: 'Actions Rapides',
    admin_recent_messages: 'Messages Récents',
    admin_system_status: 'Statut du Système',
    admin_all_systems_operational: 'Tous les Systèmes Opérationnels',
    admin_online: 'En Ligne',
    admin_storage_usage: 'Utilisation du Stockage',
    admin_manage_inventory: 'Gérez votre inventaire de véhicules',
    admin_manage_listings: 'Gérez vos annonces de propriétés',
    admin_manage_offerings: 'Gérez les offres de conciergerie',
    admin_manage_inquiries: 'Gérez les demandes des clients',
    admin_manage_accounts: 'Gérez les comptes administrateur',
    admin_global_settings: 'Gérer la configuration globale du site',
    admin_car_name: 'Nom de la Voiture',
    admin_folder_name: 'Nom du Dossier',
    admin_year: 'Année',
    admin_transmission: 'Transmission',
    admin_color: 'Couleur',
    admin_images_upload: 'Téléchargement d\'Images (4-6 images)',
    admin_images_count: 'images',
    admin_reply_via_email: 'Répondre par E-mail',
    admin_reply_via_whatsapp: 'Répondre par WhatsApp',
    admin_new_car: 'Ajouter une Nouvelle Voiture',
    admin_edit_car: 'Modifier la Voiture',
    admin_new_property: 'Ajouter une Nouvelle Propriété',
    admin_edit_property: 'Modifier la Propriété',
    admin_new_service: 'Ajouter un Nouveau Service',
    admin_edit_service: 'Modifier le Service',
    admin_no_messages: 'Aucun message pour le moment',
    admin_no_listings: 'Aucune annonce pour le moment',
    admin_name: 'Nom',
    admin_role: 'Rôle',
    admin_status: 'Statut',
    admin_created: 'Créé',
    admin_actions: 'Actions',
    admin_active: 'actif',
    admin_inactive: 'inactif',
    admin_site_name: 'Nom du Site',
    admin_default_language: 'Langue par Défaut',
    admin_logo_upload: 'Téléchargement du Logo',
    admin_current_theme: 'Thème Actuel',
    admin_dark_mode: 'Mode Sombre',
    admin_light_mode: 'Mode Clair',
    admin_primary_color: 'Couleur Principale (Or)',
    admin_secondary_color: 'Couleur Secondaire (Violet)',
    admin_contact_info: 'Informations de Contact',
    admin_whatsapp: 'WhatsApp',
    admin_address: 'Adresse',
    admin_save_settings: 'Enregistrer les Paramètres',
    admin_settings_saved: 'Paramètres enregistrés avec succès',
    admin_manage_inventory_desc: 'Gérez votre inventaire de véhicules',
    admin_manage_listings_desc: 'Gérez vos annonces de propriétés',
    admin_manage_offerings_desc: 'Gérez les offres de conciergerie',
    admin_manage_inquiries_desc: 'Gérez les demandes des clients',
    admin_manage_accounts_desc: 'Gérez les comptes administrateur',
    admin_manage_config: 'Gérer la configuration globale du site',
    admin_client_messages: 'Messages Clients',
    admin_user_management: 'Gestion des Utilisateurs',
    admin_ready_to_experience: 'Prêt à Vivre le Luxe ?',
    admin_contact_team: 'Contactez notre équipe dès aujourd\'hui pour découvrir comment nous pouvons vous aider à trouver votre propriété ou véhicule de luxe idéal',
    // Home page translations (French)
    home_about_title: 'À Propos de Don Pépé Services',
    home_about_p1: 'Don Pépé Services est le premier marché du luxe de Dubaï, se spécialisant dans l\'immobilier exclusif, les véhicules haut de gamme et les services de conciergerie sur mesure. Avec plus de 15 ans d\'expérience au service d\'une clientèle distinguée dans le monde entier, nous sélectionnons uniquement les propriétés et véhicules les plus raffinés.',
    home_about_p2: 'Notre portefeuille comprend de magnifiques villas en bord de mer à Palm Jumeirah, des penthouses luxueux au centre-ville de Dubaï avec vue sur le Burj Khalifa, et des demeures élégantes aux Emirates Hills. Chaque propriété est soigneusement sélectionnée pour répondre aux plus hauts standards de luxe et de sophistication.',
    home_about_p3: 'Notre collection de véhicules présente les automobiles les plus exclusives du monde, des supercars en édition limitée aux véhicules de luxe sur mesure. Nous travaillons directement avec les fabricants et les collectionneurs pour vous offrir un accès à des véhicules rarement disponibles sur le marché libre.',
    home_services_subtitle: 'Expérience luxe incomparable avec notre collection exclusive de propriétés, véhicules et services',
    home_why_choose_title: 'Pourquoi Choisir Don Pépé',
    home_why_choose_subtitle: 'Ce qui nous distingue sur le marché du luxe',
    home_why_excellence: 'Excellence',
    home_why_excellence_desc: 'Service récompensé par les leaders de l\'industrie du luxe',
    home_why_trusted_network: 'Réseau de Confiance',
    home_why_trusted_desc: 'Accès à des annonces exclusives et des collections privées dans le monde entier',
    home_why_security: 'Sécurité',
    home_why_security_desc: 'Confidentialité complète et transactions sécurisées pour tous les clients',
    home_why_support: 'Support 24/7',
    home_why_support_desc: 'Équipe de conciergerie dédiée disponible 24h/24 pour vos besoins',
    home_cta_ready: 'Prêt à Vivre le Luxe ?',
    home_cta_contact: 'Contactez notre équipe dès aujourd\'hui pour découvrir comment nous pouvons vous aider',
    home_cta_get_started: 'Commencer',
    // Services page translations (French)
    services_search_placeholder: 'Rechercher des voitures par nom, marque ou modèle...',
    services_search_no_results: 'Aucune voiture ne correspond à votre recherche.',
    services_search_found: 'Trouvé {count} {plural}',
    services_search_found_car: 'voiture',
    services_search_found_cars: 'voitures',
    services_no_results_title: 'Aucune voiture ne correspond à votre recherche',
    services_no_results_desc: 'Essayez d\'ajuster vos critères de recherche ou parcourez tous nos véhicules de luxe',
    services_clear_search: 'Effacer la Recherche',
    services_vehicles_desc: 'Des supercars en édition limitée aux véhicules de luxe sur mesure',
    services_beds: 'Chambres',
    services_baths: 'Salles de Bain',
    services_sqft: 'pi²',
    // Contact page
    concierge_service_inquiry: 'Demande de Service de Conciergerie',
    // Common UI elements
    logo_alt: 'Logo Don Pépé',
    admin_login_portal: 'Don Pépé Admin',
    admin_login_access: 'Portail d\'Accès Sécurisé',
    admin_login_error: 'Échec de la connexion. Veuillez vérifier vos identifiants.',
    admin_login_submit: 'Se Connecter',
  }
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en'
  })

  useEffect(() => {
    localStorage.setItem('language', language)
    document.documentElement.lang = language
    // Update document title and meta description for SEO when language changes
    const title = translations[language]?.site_name
    if (title) document.title = title
    const desc = translations[language]?.meta_description
    if (desc) {
      let meta = document.querySelector('meta[name="description"]')
      if (!meta) {
        meta = document.createElement('meta')
        meta.name = 'description'
        document.head.appendChild(meta)
      }
      meta.content = desc
    }
  }, [language])

  const t = (key) => {
    return translations[language]?.[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}

